/**
 * 200 feed posts for 21.05.2026 — humor, life, crypto communities, advice + CTA.
 * Used by seedFeed.js
 */

const USERNAME_POOL = [
  'cryptoalpha',
  'solwhale_io',
  'defi_chad',
  'btc_oracle_ru',
  'memecoin_hunter',
  'chainscout',
  'altseason_io',
  'onchain_anna',
  'perp_master',
  'web3_daily',
  'eth_maxi',
  'layer2_lisa',
  'macro_mike',
  'sol_degen_ru',
  'funding_watcher',
  'stable_sage',
  'nft_flipper',
  'base_builder',
  'riven_trades',
  'orbit_eth',
  'nova_macro_ru',
  'airdrop_ace',
  'restaking_ray',
  'pepe_signals',
  'arb_alex',
  'yield_yuki',
  'volkov_trade',
  'katya_onchain',
  'miner_x_ru',
  'luna_defi_ru',
  'chart_master_ru',
];

const COMMUNITIES = [
  { handle: 'memecoin-lab', name: 'Memecoin Lab', topic: 'мемкоины и нарративы' },
  { handle: 'defi-perps-hub', name: 'DeFi & Perps Hub', topic: 'DeFi и перпы' },
  { handle: 'btc-macro-desk', name: 'BTC Macro Desk', topic: 'BTC и макро' },
  { handle: 'sol-degen-zone', name: 'SOL Degen Zone', topic: 'Solana и деген' },
  { handle: 'trading-floor', name: 'Trading Floor', topic: 'трейдинг и риск-менеджмент' },
  { handle: 'yield-masters', name: 'Yield Masters', topic: 'доходность и стейблы' },
  { handle: 'perp-academy', name: 'Perp Academy', topic: 'фандинг и ликвидации' },
  { handle: 'onchain-radar', name: 'Onchain Radar', topic: 'ончейн-потоки' },
];

const HUMOR = [
  'Портфель в минусе, но настроение в плюсе — это же диверсификация эмоций?',
  'Купил «дип». Оказалось, это был только первый этаж лестницы вниз.',
  'Сказал жене, что занят «риск-менеджментом». На самом деле смотрю, как свеча краснеет быстрее меня.',
  'Мой трейдинг-план: купить, пережить, рассказать друзьям, что это было «долгосрок».',
  'Funding negative? Значит, рынок платит мне за терпение. Логика железная.',
  'Открыл график на 5 минут — закрыл через два часа. Time management level: crypto.',
  'Думал, что FOMO — это новый тикер. Оказалось, lifestyle.',
  'Кофе $5, газ $12, сделка -$40. Завтрак дорогой, но образ жизни премиальный.',
  'HODL — это когда ты держишь позицию и одновременно держишь себя в руках.',
  'Биржа сказала «Maintenance». Я тоже на maintenance, только душевный.',
  'Поставил алерт на $100k BTC. Проснулся — алерт сработал. На $94k. Близко, но не то.',
  'Мемкоин вырос на 400%. Я вырос как личность — научился не хвастаться до фиксации.',
  '«Это не потеря, пока не продал» — мой любимый афоризм и худший совет себе.',
  'Chart said breakout. Wallet said goodbye. We are not the same.',
  'План на день: спорт, вода, медитация. Факт: funding, OI, Twitter, regret.',
  'Когда говорят «мы в early» — проверяю, не early ли я в очереди на ликвидацию.',
  'Stables не падают. Падает только моя уверенность в тайминге входа.',
  'Сегодня рынок в боковике. Я тоже — между «докупить» и «хватит».',
  'NFT floor down. My floor mood also down. Correlation 1.0.',
  'Продал на локальном дне, купил на локальном хае. Я — market maker для себя.',
  'Жизнь коротка, свечи длинные, стопы короткие — баланс найден.',
  'Мой DeFi yield: 12% APY и 100% ANX (Annual Nagging Yield) от близких.',
  'Проснулся — BTC +2%. Улыбнулся. Открыл 15m — BTC -1%. Нейтральный день.',
  '«Just a small position» — famous last words before the margin call.',
  'Рынок: risk-on. Я: snack-on. Но хотя бы один из нас последователен.',
  'Листал ленту 20 минут — уже эксперт. Открыл терминал — уже сомневающийся эксперт.',
  'Дип — это когда ты уверен. Дип-дип — когда ты тихо материшься.',
  'Сегодня без сделок. Называю это «альфа через отсутствие ошибок».',
  'Купил токен «для смеха». Смех дорогой, но мемы качественные.',
  'Баг в голове: думать, что следующий раз точно зайду по плану.',
  'Портфель как Netflix: много серий, финал непредсказуемый.',
  'Когда funding 0.01% — спокойно. Когда 0.1% — уже драма в чате.',
  'Мой stop-loss — это психологическая граница, которую рынок обожает тестировать.',
  'Вчера был умный. Сегодня рынок напомнил, что умность временная.',
  'Трейдинг — это спорт. Я пока в любительской лиге с премией «учусь».',
  'Сказал «последняя сделка на сегодня». Сделок было ещё четыре. Классика.',
  'Лучший индикатор — сон. Не выспался — не торгую. Работает 50% времени.',
  'Мой TA: если страшно — уменьши размер. Если не страшно — тоже уменьши.',
  'Рынок дал урок. Я поставил лайк и пошёл пить чай — зрелость растёт.',
  'Планировал retire early. Пока retire from trading на выходные.',
  'Whale moved. I moved… to the couch to watch the chart.',
  'Говорят «touch grass». Я touch chart. Same energy, different trauma.',
  'Позиция в плюсе — я гений. В минусе — «рынок манипулирует». Стабильная личность.',
  'Сегодня только наблюдаю. Наблюдательный пункт — мой любимый режим survival.',
  'Купил на новости. Продал на эмоции. Бизнес-модель хрупкая, но честная.',
  'Мой любимый таймфрейм — тот, где меньше видно моих ошибок.',
  'Ликвидность низкая, уверенность высокая — опасный коктейль, но ароматный.',
  'Если бы PnL конвертировался в сон — я бы спал вечно.',
  'Рынок: chop. Я: chips. Snack and watch.',
  '«Это финальная ликвидация» — сказал я в третий раз за месяц.',
  'Добавил в watchlist ещё 30 тикеров. Продуктивность через FOMO.',
  'Сегодня без leverage. Горжусь собой как родительом, который не дал ребёнку сладкое.',
  'Мем: «buy the dip». Реальность: dip купил меня.',
  'Обед, прогулка, вода — self-care. Потом funding и existential crisis — crypto-care.',
  'Мой portfolio color today: сезон «красный осенний».',
  'Сделал breakeven и рад как будто +50%. Маленькие победы.',
  'Когда все в панике — я в чате с мемами. Emotional support as a service.',
  'График рисует треугольник. Я рисую надежду. Искусство живо.',
  'Суббота. Рынок открыт 24/7. Отдых — optional DLC.',
  'Поставил take-profit. Рынок поставил «plot twist». Сюжет богатый.',
  'Жизнь: встать, умыться, улыбнуться. Крипта: проснуться, чекнуть BTC, вздохнуть, улыбнуться сквозь боль.',
  'Мой risk/reward: рискую настроением, награда — опыт. Иногда дорогой.',
  '«One more candle» — и вот уже полночь. Time flies when you baghold.',
  'Сегодня рынок учит терпению. Я — не самый талантливый ученик, но стараюсь.',
  'Продал альт, он вырос. Купил альт, он уснул. Я — catalyst для обратных движений.',
  'Лучший hedge — выключить уведомления. Проверено вчера в 3:00.',
  'Думал войти. Не вошёл. Цена улетела. Мораль: рынок не обязан платить за мою дисциплину.',
  'Мой любимый stablecoin — стабильное «не трогать терминал».',
  'Когда говорят «wen moon» — я отвечаю «wen nap». Priorities.',
  'Портфель: long hope, short patience. Unbalanced but relatable.',
  'Сегодня я — liquidity для чужих мемов. Завтра может быть наоборот. Цикл.',
  'Открыл позицию, закрыл Twitter. Health hack.',
  'Рынок green. Я green with envy к тем, кто вошёл раньше. Human nature.',
  'Сделка +2%. Праздную чаем. Сделка -2%. Тоже чаем. Tea is the real stablecoin.',
  'План: не overtrade. Факт: overthink. Progress?',
  'Мой TA tool #1 — здравый смысл. Tool #2 — offline mode.',
  'Если бы за каждый «ещё чуть-чуть подожду» платили — я был бы whale.',
  'Сегодня рынок как погода: обещали солнце, идёт дождь, зонт (стоп) забыли.',
  'Крипта научила английскому: liquidation, funding, cope — essential vocabulary.',
  'Вечер. Свечи. Тишина. И внезапно — volume spike. Romance.',
  'Мой stop — не цена, а момент, когда перестаю верить в сценарий. Философски.',
  '«Это не казино» — говорят люди, которые никогда не сидели в funding во время новостей.',
  'Сегодня без мемов в портфеле. Только мемы в голове. Balance.',
  'Жизненный совет: пей воду. Трейдинг-совет: пей воду до маржин-колла.',
  'Я не упал — я тестировал поддержку. Так говорю я и график.',
  'Когда BTC flat — я flat emotionally. Синхронизация идеальная.',
  'Лучшая сделка дня — та, которую не открыл. Buddha mode.',
  'Мой port: 40% BTC, 30% ETH, 30% «ну посмотрим». Professional allocation.',
  'Рынок: volatility. Я: volatility в голосе при открытии приложения.',
  'Сегодня learn only. Tomorrow maybe earn. Classic roadmap.',
  'Поставил alert. Забыл звук выключить. Соседи теперь тоже следят за BTC.',
  'Дип купил, ралли продал, ралли снова купил — circle of crypto life.',
  'Если сделка идеальная в ретроспективе — значит, я её не делал.',
  'Мой favorite pattern — выходные без импульсивных входов. Rare pattern.',
  'Говорю семье: «инвестиции». Имею в виду: «образование через ошибки».',
  'Сегодня рынок дал +1% надежды и -0% уверенности. Fair trade.',
  'Когда листаешь ленту час — это research. Когда два — procrastination. Science.',
  'Мой cold wallet — холодный. Hot takes — горячие. Temperature diversity.',
  'Проснулся рано — альфа. Проснулся и сразу в терминал — beta.',
  'Лучший trade size — тот, после которого спишь нормально.',
  'Сегодня я — bear на импульсивность, bull на чай.',
  'Рынок: «no clear trend». Я: «no clear plan». Match made in heaven.',
  'Мемкоин назвался «safe». Irony appreciated.',
  'Сделал unwind позиции. Настроение тоже unwind. Holistic trading.',
  'Если бы стресс сжигал калории — я был бы athletic.',
  'Сегодня только читаю чат. Иногда лучший PnL — social, не financial.',
  'Мой edge — умение шутить, когда port красный. Coping strategy OP.',
  'Пятница: можно расслабиться. Крипта: «hold my beer».',
  'План на выходные: отдых. BTC: «а что если новость?»',
  'Я не тильтую — я эмоционально волатилен. Rebrand successful.',
  'Сегодня market cap рынка большой. Мой cap на ошибки — маленький. Growth mindset.',
  'Купил «на откате». Откат купил ещё три отката. Matryoshka trading.',
  'Лучший friend в chop — cash. Second best — memes.',
  'Свеча доджи. Я тоже в нейтральной позе — между buy и sell.',
  'Сегодня без прогнозов. Только наблюдения и уважение к стопам.',
  'Мой portfolio performance: strongly tied to screen time. Need detox.',
  'Когда все short — я long peace of mind. Contrarian irl.',
  'Рынок открыл gap. Я открыл окно — свежий воздух тоже alpha.',
  '«Trust the process» — процесс пока trust issues.',
  'Сегодня я — spot trader emotions, futures market reality. Split personality.',
  'Лучший indicator снова оказался «не торговать уставшим».',
  'Мой любимый exchange feature — кнопка «close position». Poetry.',
  'Жизнь прекрасна за пределами order book. Напоминание себе.',
  'Сделка закрыта. Глаза закрыты. Balance restored.',
  'Если бы за терпение платили stablecoins — я был бы богат.',
  'Сегодня рынок: meh. Я: meh but smiling. Upgrade.',
  'Крипта — единственное место, где «to the moon» и «touch grass» coexist.',
  'Мой stop hunt — это когда ищу оправдание не закрыть сделку.',
  'Вечерний ритуал: закрыть ноут, открыть телефон, закрыть телефон, открыть ноут.',
  'Сегодня без leverage — чувствую себя гражданином спокойной вселенной.',
  'Портфель как gym membership: плачу, хожу редко, надеюсь на результат.',
  'Funding positive — радуюсь. Negative — тоже радуюсь («дешёвый лонг»). Flexible happiness.',
  'Мой TA: higher highs in hope, lower lows in discipline. Mixed chart.',
  'Сегодня learn from others\' mistakes. Convenient and cheap.',
  'Рынок green, трава green, настроение green. Rare alignment.',
  '«Last trade» today was a lie. But a beautiful lie.',
  'Сон 8 часов — best trade setup. Executed poorly, will retry.',
  'Мой risk manager — будильник «иди спать».',
  'Сегодня я — observer. Tomorrow — participant. Day after — philosopher.',
  'Когда chart flat — life can be non-flat. Go outside, legends say.',
  'Продал на эмоции, купил на эмоции — emotional arbitrage.',
  'Мой port в chop. Я в chop suey mood. Cultural crossover.',
  'Сегодня без hot takes. Only warm takes and tea.',
  'Лучший community — где можно посмеяться над собой и рынком. Healing.',
  'BTC +0.5% — «bull market». BTC -0.5% — «bear market». Twitter speedrun.',
  'Мой edge case — когда не торгую, edge появляется сам.',
  'Сегодня рынок учит скромности. Урок принят, домашка завтра.',
  'Если бы PnL был калориями — диета строгая.',
  'Мой favorite altcoin — alt + «ernative plan for the evening».',
  'Сделал journal сделки. Настроение: «больше не надо». Journal works.',
  'Рынок: uncertainty. Я: certainty что нужен перерыв.',
  'Сегодня только vibes and risk management. Vibes bullish on tea.',
  'Мем: «have plan». Реальность: plan has me.',
  'Когда gas high — chain rich, wallet poor. Philosophy.',
  'Сегодня я — beta to market, alpha to friends\' memes.',
  'Лучший hedge против FOMO — список «зачем мне эта сделка».',
  'Свеча зелёная. Я зелёный от зависти к тем, кто внутри раньше. Growth area.',
  'Портфель: diversified between hope, cope, and discipline. Rebalancing daily.',
  'Сегодня market gave lesson. I gave applause and closed terminal.',
  'Мой stop-loss сработал. Эго тоже. Double win.',
  'Жизнь: не только графики. Но графики — сильная часть вечера, признаю.',
  'Сегодня без прогнозов цены — только прогноз: буду пить воду.',
  'Крипта научила терпению. Жизнь научила крипте терпению. Full circle.',
  'Мой port red. Sky blue. Balance in nature.',
  '«Just checking price» — three hours later. Classic genre.',
  'Сегодня я — spot on self-irony, futures on discipline.',
  'Лучший trade — shared joke in community chat. ROI emotional 100%.',
  'Рынок chop. Я chop vegetables for dinner. Productive pivot.',
  'Сегодня без FOMO. With JOMO (joy of missing out on bad trades).',
  'Мой TA line — линия между «войду» и «не надо». Thin line.',
  'Сегодня рынок: calm. Я: calmer. Meditation unlocked?',
  'Если бы за каждый правильный skip entry платили — богатство.',
  'Мой port: long learning, short ego. Finally good ratio.',
  'Сегодня sunset > candlestick sunset. Rare alpha irl.',
  'Крипта — marathon. Я пока на разминке с мемами.',
  'План: profit. Fact: character development. Still W.',
  'Сегодня я — bull on rest, bear on impulsive clicks.',
  'Лучший stable — stable sleep schedule. Working on it.',
  'Рынок open 24/7. My sanity: maintenance mode weekends.',
  'Сегодня без leverage, with leverage on jokes only.',
  'Мой port и я — в healthy relationship: иногда не смотрим друг на друга.',
  'Сделка закрыта в ноль. Назову это «плата за образование».',
  'Сегодня рынок: mixed. Я: mixed nuts and optimism.',
  'Когда все кричат «moon» — я шепчу «risk per trade».',
  'Мой favorite timeframe — after market reflection, before bed.',
  'Сегодня learn, tomorrow earn, someday sleep 8h. Roadmap.',
  'Портфель как playlist: shuffle, skip, repeat emotional tracks.',
  'Сегодня я — liquidity provider of good vibes in chat.',
  'Мемкоин up. Ego up. Memecoin down. Ego down. Correlation therapy.',
  'Лучший indicator — «мама сказала отдохнуть».',
  'Сегодня market meh, coffee great. Priorities sorted.',
  'Если бы за смех в red day платили — я бы фондировал рынок.',
  'Мой stop — цена. Мой real stop — усталость. Listen to both.',
  'Сегодня без hot takes, cold brew only.',
  'Рынок taught patience. I taught market my absence. Fair.',
  'Жизнь больше, чем PnL. Но PnL сегодня тоже part of life. Ok.',
  'Сегодня я — spot on humor, futures on discipline tomorrow.',
  'Лучший community moment — когда все смеются над рынком вместе.',
  'BTC flat. Soul flat. Tea steeping. Triangle of peace.',
  'Сегодня no trade, no FOMO, no drama. Triple achievement.',
  'Мой port: 50% assets, 50% «we\'ll see». Honest accounting.',
  'Сегодня рынок: teacher. Я: student with snacks.',
  'Когда chart scary — zoom out on life. Works sometimes.',
  'Сегодня я — bear on overtrading, bull on friendship.',
  'Мой edge — stop when bored. Boredom saves accounts.',
  'Сегодня sunset walk > watching one more candle. IRL alpha.',
  'Портфель red, shirt red (coincidence), mood recovering.',
  'Сегодня market chop. I chop procrastination. Productive.',
  '«One more scroll» — gateway to FOMO. Guard rails on.',
  'Сегодня я — observer with popcorn, not participant with leverage.',
  'Лучший stablecoin — stable nerves. Mining in progress.',
  'Сегодня без predictions. Only good vibes and water.',
  'Мой TA: trend up on self-care, trend down on impulse.',
  'Сегодня рынок gave nothing. I gave myself break. Win-win.',
  'Крипта — hobby, work, sport, meditation. Multitool.',
  'Сегодня laugh at past trades. Tomorrow past today\'s trades. Cycle of maturity.',
  'Мой port small, dreams big, memes huge. Balanced ecosystem.',
  'Сегодня community > chart. Social alpha underrated.',
  'Рынок: volatile. Я: volatile only before coffee. Improvement.',
  'Сегодня last scroll at 22:00. Discipline speedrun any%.',
  'Мой favorite pattern — weekend without revenge trading.',
  'Сегодня life advice: call a friend. Crypto advice: check risk.',
  'Портфель как weather: cloudy, maybe sun later.',
  'Сегодня я — long on patience, short on noise.',
  'Мем: «trust me bro». Bro: «use stop loss».',
  'Сегодня market quiet. Mind quieter. Progress.',
  'Лучший trade idea — the one you slept on and skipped.',
  'Сегодня green tea, not only green candles. Wellness meta.',
  'Мой port и Netflix: both «one more episode» energy.',
  'Сегодня без doomscroll, with hopescroll in community.',
  'Рынок open. Kitchen open. Sandwich alpha first.',
  'Сегодня я — spot on boundaries, perp on jokes only.',
  'Если бы терпение торговалось — я бы на CEX top volume.',
  'Сегодня chart flat, pizza round. Geometry of happiness.',
  'Мой stop hunt — hunting for excuses. Season closed.',
  'Сегодня learn from chat, not only from candles.',
  'Портфель: work in progress. Like me. Relatable.',
  'Сегодня bullish on friends, neutral on price, bear on FOMO.',
  'Мой risk/reward on memes: infinite joy / zero cost.',
  'Сегодня market lesson free. Tuition paid earlier. Ok.',
  'Лучший hedge — hobby outside crypto. Remembered today.',
  'Сегодня я — bull on kindness, chop on chart.',
  'Мой port red, heart still full. Important metric.',
  'Сегодня no alpha hunt, only nap hunt. Valid strategy.',
  'Рынок: uncertain. Dinner: certain. Priorities.',
  'Сегодня smile > PnL. But PnL also checked, I\'m human.',
  'Мой favorite exchange — exchange of memes in community.',
  'Сегодня life > leverage. Posted and believed.',
  'Крипта научила English. Life научила Russian «хватит на сегодня».',
  'Сегодня я — liquidity of laughter in group chat.',
  'Мой port: small bets, big lessons. Tuition worth it?',
  'Сегодня market meh, dog happy. Dog right.',
  'Лучший indicator — dog wants walk. Bullish on walk.',
  'Сегодня without «wen moon», with «when walk».',
  'Мой TA: support at tea, resistance at overtrading.',
  'Сегодня community saved mood. Join yours — link below vibes.',
  'Портфель как gym: motivation Monday, reality Friday.',
  'Сегодня I choose peace. Chart can wait.',
  'Мем: diamond hands. Reality: paper nerves. Both ok.',
  'Сегодня market chop. I chop onions. Chef mode.',
  'Лучший stable — stable friendship in bear market.',
  'Сегодня bullish on nap, bearish on 3am chart check.',
  'Мой port: learning curve steep, ego curve flattening.',
  'Сегодня sunset > funding rate. Fight me.',
  'Рынок: teacher strict. Я: student with sense of humor.',
  'Сегодня no trade hero, rest hero. Cape optional.',
  'Мой edge — knowing when to close app. Practicing.',
  'Сегодня life tip: stretch. Crypto tip: stretch risk limits not sanity.',
  'Портфель red, playlist loud, mood recovering. Therapy.',
  'Сегодня I\'m exit liquidity for bad ideas only — by not trading.',
  'Мой favorite coin — coin of good advice from community.',
  'Сегодня market flat, pancakes stacked. Bullish breakfast.',
  'Когда все panic — I panic-buy snacks. Different strategy.',
  'Сегодня long on humor, short on toxicity. Good ratio.',
  'Мой stop — when joke stops being funny and fear starts.',
  'Сегодня community chat > terminal. Social yield.',
  'Рынок 24/7. My bed also 24/7 available. Competition.',
  'Сегодня without predictions, with gratitude. Rare post.',
  'Мой port: diversified in lessons. Returns TBD.',
  'Сегодня green mood > green candle. Health meta.',
  'Лучший trade — compliment to stranger. ROI karma.',
  'Сегодня I touch grass. Chart touches my heart later.',
  'Мем: «few understand». Few understand my sleep schedule too.',
  'Сегодня market quiet, mind loud — meditating that down.',
  'Мой risk manager — friend who says «go sleep».',
  'Сегодня bullish on boundaries, bearish on 100x.',
  'Портфель как cloud: shape changes, still floating.',
  'Сегодня laugh, hydrate, repeat. Not financial advice.',
  'Мой favorite chain — chain of good habits. Building.',
  'Сегодня no FOMO, yes JOMO, maybe tea MO.',
  'Рынок chop. Life not chop. Good separation.',
  'Сегодня I\'m spot on self-care, perp on tomorrow\'s discipline.',
  'Мой port small, community big. Net positive.',
  'Сегодня chart meh, people great. Choose people.',
  'Лучший airdrop — drop of kindness. Cheesy but true.',
  'Сегодня market gave 0%, I gave 100% to hobby. Fair swap.',
  'Мой TA: trend up on naps, down on noise.',
  'Сегодня without hot take, with warm blanket.',
  'Крипта — part of life, not whole life. Reminder post.',
  'Сегодня smile at red port. Revolutionary act.',
  'Мой stop-loss on stress — activated. Works.',
  'Сегодня community promo: join for memes AND risk tips. Both.',
  'Рынок: uncertain. Pizza: certain delivery. Hedge.',
  'Сегодня I\'m bull on patience, bear on impulse buys.',
  'Мой port: under construction, like my sleep schedule.',
  'Сегодня last candle watched at reasonable hour. Growth.',
  'Лучший indicator — feeling «не надо сделку». Trust it.',
  'Сегодня life > chart. Chart still checked tho. Human.',
  'Мем: «buy fear». Me: «buy snacks during fear».',
  'Сегодня market flat, soul upgrading. Patch notes: rest.',
  'Мой favorite volatility — volatility of jokes in chat.',
  'Сегодня without leverage on nerves only.',
  'Портфель red, humor green. Net emotional positive.',
  'Сегодня learn, don\'t burn. Motto.',
  'Мой edge — admitting «не знаю» быстрее других.',
  'Сегодня sunset walk alpha > any perp alpha.',
  'Рынок open. Window open. Fresh alpha air.',
  'Сегодня I choose community over chart for 1 hour. Won.',
  'Мой port: long humanity, short arrogance. Rebalance ok.',
  'Сегодня no moon post, only «drink water» post. Useful.',
  'Лучший stable — stable mood after logging off.',
  'Сегодня market chop, I chop stress with walk.',
  'Мой risk: overthinking. Reward: not trading. Win.',
  'Сегодня bullish on friends who send memes when port red.',
  'Портфель как weather app: «возможны осадки», зонт = стоп.',
  'Сегодня I\'m exit from bad habits, not exit liquidity.',
  'Мой favorite funding — funding good conversations.',
  'Сегодня chart closed, life opened. Try it.',
  'Крипта serious. Я seriously need snack. Balance.',
  'Сегодня community CTA: join, laugh, learn. Triple threat.',
  'Мой port red, playlist «chill» green. Coping mastered.',
  'Сегодня without «to the moon», with «to the park».',
  'Рынок: meh. Memes: great. Allocation clear.',
  'Сегодня long on kindness, short on panic posts.',
  'Мой stop hunt ended. Found stop at «go offline».',
  'Сегодня life advice + crypto advice: sleep first, chart second.',
  'Портфель: version 0.9 beta. Patience for v1.0.',
  'Сегодня I\'m whale in jokes, shrimp in port. Accept.',
  'Лучший trade — not sharing hot take I\'ll regret.',
  'Сегодня market teacher, I student, tea assistant.',
  'Мой edge case — weekend mode enabled.',
  'Сегодня bullish on «нет» себе на лишнюю сделку.',
  'Мем: «number go up». Also: «number go nap».',
  'Сегодня port chop, pizza delivery chop-chop. Happiness.',
  'Мой favorite L2 — layer of blanket tonight.',
  'Сегодня community > solo cope. Join link vibes.',
  'Рынок volatile. Soup stable. Dinner plan bullish.',
  'Сегодня I touch grass, chart touches me tomorrow.',
  'Мой port: tuition paid, degree in progress.',
  'Сегодня laugh at market, not with money on line. Safer.',
  'Лучший hedge — friends who don\'t ask PnL first.',
  'Сегодня green tea, red port, green future maybe.',
  'Мой TA: support at friends, resistance at ego.',
  'Сегодня no financial advice, only life advice: call mom.',
  'Портфель как сериал: сезон «обучение» длинный.',
  'Сегодня I\'m bull on rest, neutral on price, bear on drama.',
  'Мой stop — when eyes burn from screen. Valid.',
  'Сегодня market flat, pancakes fat. Win.',
  'Крипта 24/7. My sanity business hours only.',
  'Сегодня community saved day. Your turn — join.',
  'Мой port small, jokes large. Market cap of humor high.',
  'Сегодня without leverage, with leverage on kindness.',
  'Рынок: uncertain. Meme: certain funny. Hedge humor.',
  'Сегодня last post today — discipline or lie? We\'ll see.',
];

const LIFE = [
  'Утро началось не с графика, а с прогулки. Настроение +1, BTC подождёт.',
  'Суббота: рынок работает, я — нет. Выходной для головы, не для депозита.',
  'Приготовил завтрак, потом чекнул funding. Правильный порядок приоритетов почти.',
  'Сегодня встретился с друзьями offline. Оказалось, мир шире, чем 15m свеча.',
  'План: спорт, вода, сон. Крипта — бонус-трек, не основной саундтрек дня.',
  'Починил кран, починил настроение. Ликвидации починю завтра (шутка, стопы стоят).',
  'Дождь за окном, чай в руке, терминал закрыт. Premium lifestyle.',
  'Сегодня работа, семья, вечером — 20 минут ленты. Balance attempt.',
  'Переставил мебель — refresh интерьера дешевле, чем refresh port на импульсе.',
  'Вечер без уведомлений. Слышал только дождь и собственные мысли. Recommend.',
  'Утренняя пробежка > утренний panic sell. Not always, but today yes.',
  'Сделал список дел. Крипта внизу списка. Прогресс.',
  'Сегодня читал книгу, не thread. Глаза благодарят.',
  'Готовлю ужин. RSI готовится сам без меня.',
  'Позвонил родителям. Best risk-off asset.',
  'Субботний рынок активен, я активен на пляже (в парке). Fair.',
  'Сегодня минимум экрана, максимум солнца. Portfolio tan не считается.',
  'Навёл порядок в столе — surprisingly similar to clearing mind.',
  'Вечер: музыка, не funding. Soundtrack upgrade.',
  'Сегодня научился говорить «нет» лишней сделке и лишней встрече. Soft skills.',
  'Планировал productivity, получил rest. Acceptable bug.',
  'Утро: йога. День: работа. Вечер: 10 мин crypto. Triangle of adulting.',
  'Сегодня без сравнения с чужим PnL. Сравнил только погоду — она лучше.',
  'Прогулка с собакой. Dog doesn\'t care about BTC. Wise.',
  'Сделал meal prep на неделю. Meal prep > chart prep иногда.',
  'Сегодня compliment stranger. Karma bullish.',
  'Вечерний дневник: три хороших вещи без упоминания портфеля. Hard mode cleared.',
  'Сон 7.5 часов. Performance enhancement legal.',
  'Сегодня garden > chart. Tomatoes don\'t rekt.',
  'Помог коллеге. ROI не в $, в спокойствии.',
  'Суббота: market open, bakery open. Chose bakery first.',
  'Сегодня digital detox hour. Survived. Thrived.',
  'Убрал 200 unused tabs. Mind lighter than after breakeven trade.',
  'Вечер: настолки с друзьями. No leverage, only dice.',
  'Сегодня gratitude list longer than watchlist.',
  'Погода +15, настроение +20, port ±0. Good day.',
  'Сделал stretch every hour. Back happy, even if port not.',
  'Сегодня lunch away from desk. Revolutionary.',
  'Listening to rain > listening to liquidation alerts.',
  'Сегодня hobby: фото. Shot sunset, not screenshot of chart.',
  'План: рано лечь. Крипта: «maybe one candle». Fight tonight.',
  'Сегодня kindness > hot take. Posted kindness.',
  'Walked 8k steps. Steps > leverage.',
  'Сегодня cooked new recipe. Gas fee only in kitchen.',
  'Friends dinner. Talked about life, not only coins. Healthy.',
  'Сегодня minimal phone. Maximum present moment.',
  'Fixed bike. Transportation alpha local.',
  'Сегодня museum > mempool. Culture feed.',
  'Morning coffee ritual without chart. Pure taste.',
  'Сегодня said no to drama online. Yes to tea.',
  'Planted herbs. Growth mindset literal.',
  'Сегодня journal non-trading thoughts. Refreshing.',
  'Evening bath. Liquidation only of stress.',
  'Сегодня smiled at cashier. Small bull market of souls.',
  'Read fiction. Plot better than some tokenomics.',
  'Сегодня organized photos. Memories > screenshots of PnL.',
  'Sunset watched without phone. 10/10 would repeat.',
  'Сегодня helped neighbor. Community irl meta.',
  'Breakfast slow. Day better. Correlation noted.',
  'Сегодня no compare to influencers. Compare to yesterday me only.',
  'Playlist nostalgic. Mood up, port irrelevant for hour.',
  'Сегодня cleaned inbox. Mental bandwidth freed.',
  'Lunch with family. Love > leverage.',
  'Сегодня bike ride. Wind > market wind.',
  'Drew doodle. Creativity rekt-proof.',
  'Сегодня thanked teammate. Team > solo trading emotionally.',
  'Early sleep experiment. Hypothesis: better decisions tomorrow.',
  'Сегодня park bench > trading desk bench.',
  'Water 2L goal hit. Hydration pump.',
  'Сегодня no multitask. One thing at time. Luxury.',
  'Fixed lamp. Light both literal and metaphorical.',
  'Сегодня listened more, posted less. Growth.',
  'Homemade pizza. Dough rose, ego didn\'t need to.',
  'Сегодня watched clouds. Clouds don\'t rug.',
  'Called old friend. Timeless asset.',
  'Сегодня learned 10 words in new language. Brain flex.',
  'Morning stretch. Body version update.',
  'Сегодня gratitude for health. Top of portfolio of life.',
  'Evening without Reels. Won small battle.',
  'Сегодня organized closet. Order outside, order inside attempt.',
  'Tea ceremony mood. No ceremony for impulsive trades today.',
  'Сегодня walked instead of scrolled. Legs approved.',
  'Board games night. RNG fairer than some launches.',
  'Сегодня smiled without reason. Reason found later anyway.',
  'Cooking playlist on. Market playlist off. Balance.',
  'Сегодня helped newbie at work. Teaching heals ego.',
  'Window open. Fresh air alpha.',
  'Сегодня no toxic reply written. Victory.',
  'Sketched city. Art > chart art sometimes.',
  'Сегодня slow morning. Fast thoughts quieted.',
  'Volunteer hour. Different kind of yield.',
  'Сегодня chose book before phone in bed. Habit building.',
  'Rainy day cozy. Port rainy too but cozy still ok.',
  'Сегодня complimented myself. Awkward but useful.',
  'Fixed squeaky door. Small wins chain.',
  'Сегодня dance in kitchen. Volatility of moves high, fun higher.',
  'Planned week on paper. Paper doesn\'t liquidate.',
  'Сегодня ate vegetables. Bullish on health.',
  'Friend\'s birthday. Cake > candlestick cake.',
  'Сегодня minimal news. Maximum calm.',
  'Stargazing tonight. Stars > star tokens.',
  'Сегодня forgave small mistake. Self-compassion trade.',
  'Organized desk drawer. Found peace and old charger.',
  'Сегодня listened to podcast non-crypto. Brain vacation.',
  'Morning sun on face. Free serotonin.',
  'Сегодня wrote thank-you note. Old school bullish.',
  'Lazy Sunday earned. Not lazy on risk management tho.',
  'Сегодня plant watered. Growth delayed not denied for plant.',
  'Bike maintenance. Reliable transport > reliable narrative sometimes.',
  'Сегодня no argument online. Peace preserved.',
  'Homemade soup. Warmth internal.',
  'Сегодня watched comedy. Laughed at self too.',
  'Early farmers market. Real yield fresh tomatoes.',
  'Сегодня nap. Performance enhancing nap.',
  'Fixed typo in doc. Precision training for entries too.',
  'Сегодня beach (or river). Water sounds > notification sounds.',
  'Gift for sibling. Generosity long.',
  'Сегодня mindful breathing 5 min. Volatility of breath low.',
  'Evening stroll. Steps counted happiness not only distance.',
  'Сегодня learned recipe from mom. Heritage alpha.',
  'Decluttered apps on phone. Fewer temptation portals.',
  'Сегодня said «I don\'t know» at meeting. Honesty bullish.',
  'Cloud watching contest with kid. Kid won. Fair.',
  'Сегодня no caffeine after 14:00. Sleep future thanked.',
  'Journal: 3 wins non-financial. Solid day.',
  'Сегодня fixed bike chain. Chain of good day started.',
  'Listened to vinyl. Analog mood in digital life.',
  'Сегодня helped carry groceries. Strength training irl.',
  'Sunrise seen. Early bird doesn\'t have to trade early.',
  'Сегодня polite in traffic. Emotional stability practice.',
  'Baked cookies. House smelled like bull market.',
  'Сегодня no gossip. Energy saved.',
  'Read poetry. Rhyme > random chart rhyme sometimes.',
  'Сегодня organized bookmarks. Digital hygiene.',
  'Friendship check-in message. Support stablecoin.',
  'Сегодня walked barefoot on grass. Grounding literal.',
  'Fixed garden fence. Boundaries healthy metaphor.',
  'Сегодня slow tea, slow thoughts. Good combo.',
  'Watched documentary. Learned non-market thing.',
  'Сегодня smiled at mirror. Weird but effective.',
  'Evening stretch routine. Body maintenance mode.',
  'Сегодня chose stairs. Small health longs.',
  'Lunch outside. Vitamin D shill post.',
  'Сегодня no complaint day attempt. 80% success rate.',
  'Built IKEA shelf. Instructions harder than whitepaper sometimes.',
  'Сегодня pet cat. Purr > pump.',
  'Phone on grayscale evening. Less dopamine slot machine.',
  'Сегодня thanked barista. Micro kindness.',
  'Rain boots on. Puddles > puddles of tears from bad trade.',
  'Сегодня planned vacation. Bullish on break.',
  'Listened to grandparents story. Time horizon education.',
  'Сегодня cleaned car. Fresh start energy.',
  'Morning pages writing. Clarity buff.',
  'Сегодня no snooze war. Won waking up.',
  'Picnic planned. Basket > basket of liquidations.',
  'Сегодня honest conversation. Vulnerability alpha.',
  'Watered office plant. Green thumb xp.',
  'Сегодня chose silence in elevator. Micro meditation.',
  'Fixed headphones. Music return buff.',
  'Сегодня donated old clothes. Light closet light mind.',
  'Cooking with partner. Teamwork skill transferable to trading team?',
  'Сегодня watched moon. Moon not token but still beautiful.',
  'Said sorry first. Conflict resolution speedrun.',
  'Сегодня minimal makeup / minimal ego same energy.',
  'Bike to work. Carbon neutral and calm neutral.',
  'Сегодня enjoyed silence. Rare commodity.',
  'Learned card trick. Magic > magic internet money moment.',
  'Сегодня no late night scroll pledge. Broken? We\'ll see tonight.',
  'Breakfast with view. View > viewing order book.',
  'Сегодня helped tourist with directions. Good karma deposit.',
  'Organized spices. Chaos reduced in kitchen corner.',
  'Сегодня laughed at old photos. Time capitol gains emotional.',
  'Evening tea with honey. Sweet without sugar rush trade.',
  'Сегодня fixed typo in resume. Career chain upgrade.',
  'Walked dog extra block. Dog happiness = owner happiness.',
  'Сегодня no elevator. Leg day accidental.',
  'Listened to bird song. Nature\'s notification pleasant.',
  'Сегодня called dentist. Adulting bullish.',
  'Made bed. Small order ritual.',
  'Сегодня enjoyed lunch alone. Introvert recharge.',
  'Planned gift for friend. Anticipation joy.',
  'Сегодня no road rage. Emotional margin healthy.',
  'Watched kids play. Simplicity alpha.',
  'Сегодня drank water before coffee. Revolutionary order.',
  'Fixed loose button. Attention to detail training.',
  'Сегодня sunset photo no filter. Beauty honest.',
  'Shared food. Generosity protocol.',
  'Сегодня learned neighbor name. Community irl.',
  'Quiet hour after work. Decompress successful.',
  'Сегодня no sarcasm hurtful. Soft communication.',
  'Read kid bedtime story. Best ROI.',
  'Сегодня smelled rain. Nostalgia bullish.',
  'Tried new tea. Small adventure safe.',
  'Сегодня thanked past self for saving emergency fund.',
  'Walk without destination. Freedom feeling.',
  'Сегодня minimal wardrobe choice. Less decision fatigue.',
  'Heard live music street. Free concert.',
  'Сегодня forgave traffic jam. Patience xp.',
  'Organized cables. Chaos -1.',
  'Сегодня enjoyed shower thinking. Shower thoughts asset.',
  'Called friend just because. Connection > connection wallet.',
  'Сегодня no junk food. Body thanked.',
  'Watched leaves move. Meditation free.',
  'Сегодня planned healthy week meals. Prep buff.',
  'Smiled at neighbor. Micro community.',
  'Сегодня fixed bike light. Safety first always.',
  'Enjoyed thunder from distance. Safe cozy.',
  'Сегодня no brag post. Humility practice.',
  'Learned joke. Shared joke. Day brighter.',
  'Сегодня early to appointment. Respect time.',
  'Made playlist for friend. Thoughtful.',
  'Сегодня no negative self-talk hour. Hard mode.',
  'Ate fruit. Natural sweets.',
  'Сегодня watched handpan video. Calm imported.',
  'Wrote postcard. Analog social network.',
  'Сегодня stretched neck. Trader hygiene.',
  'Enjoyed cold water splash face. Wake up gentle.',
  'Сегодня no multitask eating. Taste +100%.',
  'Fixed squeak chair. Focus +1.',
  'Сегодня thanked teacher memory. Gratitude long shelf life.',
  'Walked in light rain. Refresh.',
  'Сегодня no impulse amazon. Wallet thanked.',
  'Slept with phone away. Brave.',
  'Сегодня enjoyed breakfast silence.',
  'Helped carry stroller stairs. Good human buff.',
  'Сегодня learned new shortcut home. Efficiency.',
  'Watched cloud shapes. Creative rest.',
  'Сегодня no complain about weather. Acceptance.',
  'Made friend laugh. Best metric.',
  'Сегодня organized notes app. Mental RAM freed.',
  'Drank herbal tea evening. Sleep prep.',
  'Сегодня smiled at delivery person. Respect labor.',
  'Read quote, felt inspired, didn\'t force trade. Wise.',
  'Сегодня minimal jewelry, maximal calm.',
  'Heard friends laugh in voice chat non-crypto topic. Wholesome.',
  'Сегодня fixed mirror. Self reflection literal clean.',
  'Enjoyed homemade bread smell. Bakery alpha domestic.',
  'Сегодня no selfie obsession. Present.',
  'Planned morning routine card. Boring is good sometimes.',
  'Сегодня thanked body for carrying me. Weird gratitude works.',
  'Evening no blue light 1h. Experiment.',
  'Сегодня walked to buy milk not doomscroll. Win.',
  'Shared umbrella. Kindness liquid.',
  'Сегодня enjoyed music in headphones eyes closed.',
  'Cleaned glasses. Clarity metaphor ok.',
  'Сегодня no interrupt people. Listen skill.',
  'Ate slowly. Digestion bullish.',
  'Сегодня watched ants work. Discipline lesson free.',
  'Fixed tap drip. Waste reduced.',
  'Сегодня called cousin. Family chain strong.',
  'Enjoyed cool breeze window. AC off save planet and bill.',
  'Сегодня no toxic productivity guilt. Rest ok.',
  'Made tea for guest. Hospitality.',
  'Сегодня learned city history fact. Culture xp.',
  'Wrote down worry then tore paper. Ritual silly effective.',
  'Сегодня no compare body to ads. Self peace.',
  'Heard «thank you» and meant «you\'re welcome». Loop good.',
  'Сегодня planned screen-free morning tomorrow. Ambitious.',
  'Enjoyed starless cloudy sky still pretty.',
  'Сегодня minimal notifications settings tightened. Freedom.',
  'Ate lunch without video. Taste returned.',
  'Сегодня forgave self old mistake. Moving on.',
  'Walked after dinner. Digest + mood.',
  'Сегодня no gossip listening. Ears clean.',
  'Fixed lamp bulb. Light returned.',
  'Сегодня enjoyed child drawing on fridge. Art gallery home.',
  'Said «good night» to family. Connection.',
  'Сегодня no midnight snack chart combo. Progress.',
  'Read weather forecast not funding forecast first.',
  'Сегодня kindness comment online. Rare but done.',
  'Organized spice alphabetically. Nerd joy.',
  'Сегодня no rush. Slowness luxury.',
  'Heard rain on roof. ASMR natural.',
  'Сегодня smiled without photo proof. Authentic.',
  'Made list «what I control». Short list liberating.',
  'Сегодня no brag, no moan. Neutral peace.',
  'Enjoyed hand warmth mug. Simple pleasure.',
  'Сегодня thanked bus driver. City humanity.',
  'Watched pigeon walk funny. Free comedy.',
  'Сегодня no argue politics in chat. Sanity.',
  'Fixed zipper. Small victory wardrobe.',
  'Сегодня planned gift budget. Responsible joy.',
  'Ate apple mindfully. Crunch meditation.',
  'Сегодня no caffeine evening test. Sleep science.',
  'Called repair service early not procrastinate. Adult.',
  'Сегодня enjoyed shadow sunset long.',
  'Shared meme irl friend laughed. Offline viral.',
  'Сегодня no self-criticism hour 2pm-3pm. Treaty.',
  'Wrote 3 goals week non-money. Balance.',
  'Сегодня heard «I appreciate you». Stored heart wallet.',
  'Walked barefoot home carpet. Small comfort.',
  'Сегодня no impulse message ex. Growth.',
  'Enjoyed silence car ride. Reset.',
  'Сегодня fixed notification group mute. Peace.',
  'Drank water waking up. Habit stack start.',
  'Сегодня no negative news morning. Mood protected.',
  'Made bed hotel style. Motivation silly works.',
  'Сегодня thanked legs for walk. Body positive weird.',
  'Heard friend good news. Celebrated genuinely.',
  'Сегодня no late coffee. Tomorrow test.',
  'Organized desktop icons. Digital desk clean.',
  'Сегодня enjoyed warm socks. Cozy bullish.',
  'Read recipe cooked followed. Success rare kitchen.',
  'Сегодня no snark reply. Maturity +1.',
  'Watched moon phase app for fun not alpha.',
  'Сегодня planned friend meet next week. Anticipation.',
  'Said no extra task kindly. Boundaries.',
  'Сегодня smelled coffee beans bag. Aroma therapy.',
  'Fixed tangled necklace. Patience training.',
  'Сегодня no compare sleep to others. Rest personal.',
  'Enjoyed street musician tip. Art support.',
  'Сегодня wrote poem bad but fun. Creativity.',
  'Walked unknown street discovered cafe. Explore irl.',
  'Сегодня no phone meal 2/3. Partial win.',
  'Thanked myself for cooking. Self kindness.',
  'Сегодня heard wind trees. Nature speakers.',
  'Minimal jewelry wore favorite only. Joy small.',
  'Сегодня no rush elevator held door. Karma.',
  'Enjoyed hot shower winter memory summer daydream.',
  'Сегодня no toxic flex. Humble day.',
  'Learned friend hobby. Asked questions. Connection.',
  'Сегодня fixed typo message before send. Care.',
  'Ate vegetables lunch. Mom proud maybe.',
  'Сегодня no gossip startup. Focus own lane.',
  'Watched documentary ocean. Blue calm mind.',
  'Сегодня smiled stranger elevator. Awkward ok.',
  'Planned digital detox Sunday. Future self thanks.',
  'Сегодня no complain body. Neutral acceptance.',
  'Made tea coworker. Office community.',
  'Сегодня enjoyed lunch break outside. Sun.',
  'Heard kids laugh park. Life sound.',
  'Сегодня no impulse tweet. Thumb restraint.',
  'Fixed bike pump. Ready ride.',
  'Сегодня thanked rain for plants not mood only.',
  'Read fiction chapter. Escaped chart mentally.',
  'Сегодня no multitask shower. Weird goal achieved.',
  'Shared food photo friend not flex. Connection.',
  'Сегодня walked phone in pocket. Radical.',
  'Enjoyed candle evening no reason. Cozy.',
  'Сегодня no negative mirror talk. Treaty extended.',
  'Called friend voice not text. Warmth.',
  'Сегодня organized fridge. Food chain visible.',
  'Learned new keyboard shortcut work. Tiny win.',
  'Сегодня no road horn. Calm driver.',
  'Heard «good job» accepted without deflect. Growth.',
  'Сегодня planned healthy snack. Future hungry saved.',
  'Watched bird nest. Patience lesson.',
  'Сегодня no caffeine after 3pm trial.',
  'Fixed loose screw chair. Stable seat stable mind metaphor.',
  'Сегодня enjoyed music shower. Concert bathroom.',
  'Thanked partner small thing. Relationship maintenance.',
  'Сегодня no doom news tab. Mood guard.',
  'Walked sunset pink sky. Free NFT irl joke.',
  'Сегодня smiled for photo friend not selfie ego.',
  'Made list happy things small. Long list.',
  'Сегодня no argue price pizza split. Generous.',
  'Enjoyed cold drink shade. Summer preview.',
  'Сегодня heard owl night. Wild city.',
  'Fixed garden hose. Water flow life flow.',
  'Сегодня no midnight revenge tasks. Rest.',
  'Read kid joke book. Laughed hard.',
  'Сегодня no compare house to instagram. Peace.',
  'Shared umbrella stranger. Kindness chain.',
  'Сегодня enjoyed breakfast fruit plate colorful.',
  'Said «I need help» task. Teamwork.',
  'Сегодня no toxic hustle post. Rest valid.',
  'Heard live piano street. Culture drop.',
  'Сегодня fixed sleep mask found. Sleep buff.',
  'Enjoyed bookshop smell. Nostalgia.',
  'Сегодня no snooze 3 times. Victory marginal.',
  'Wrote gratitude 5 lines. Done.',
  'Сегодня walked dog raincoat funny. Joy.',
  'Planned healthy boundary conversation. Brave prep.',
  'Сегодня no flex car park. Humble.',
  'Ate dinner table not desk. Ritual.',
  'Сегодня heard friend vent listened only. Support.',
  'Fixed light desk lamp. Study mood.',
  'Сегодня enjoyed cloud sunset gradient. Art sky.',
  'Made friend tea visit. Connection.',
  'Сегодня no impulse online shopping cart abandoned. Win.',
  'Read poem friend sent. Culture exchange.',
  'Сегодня no self sabotage joke hurtful. Kind humor.',
  'Walked 6k steps meeting goal. Body bullish.',
  'Сегодня thanked teacher online course. Learning.',
  'Enjoyed silence morning before city noise.',
  'Сегодня no compare salary chat. Peace.',
  'Heard good news family. Happy.',
  'Сегодня fixed bike brake. Safety.',
  'Planned picnic weather permit. Joy budget low.',
  'Сегодня no late night argument online. Mature.',
  'Ate homemade lunch saved money calm.',
  'Сегодня smiled delivery tip left. Gratitude cycle.',
  'Watched moon daytime faint. Subtle beauty.',
  'Сегодня no brag workout. Just did it.',
  'Organized shoes. Entryway calm.',
  'Сегодня heard rain roof sleep aid.',
  'Called grandparent. Time precious.',
  'Сегодня no toxic friend energy invited. Boundary.',
  'Enjoyed fresh bread neighbor shared. Community irl.',
  'Сегодня minimal make-up / maximal confidence same.',
  'Fixed watch strap. Time tool ready.',
  'Сегодня no caffeine headache avoided. Water king.',
  'Read history snippet. Perspective.',
  'Сегодня walked instead uber short trip. Health + save.',
  'Thanked coworker help. Workplace culture.',
  'Сегодня no negative comment youtube. Restraint.',
  'Heard friend laugh voice note. Wholesome.',
  'Сегодня planned vacation daydream. Hope ok.',
  'Enjoyed hand cream winter skin. Self care.',
  'Сегодня no impulse DM celebrity. Sanity.',
  'Made list «done today» long. Satisfaction.',
  'Сегодня no compare gym others. Personal pace.',
  'Shared snack office. Morale food.',
  'Сегодня heard birds dawn. Alarm natural.',
  'Fixed drawer stuck. Order +1.',
  'Сегодня no road rage cut off. Breathed.',
  'Enjoyed warm laundry smell. Comfort.',
  'Сегодня called friend happy birthday on time.',
  'Walked without podcast sometimes. Thoughts allowed.',
  'Сегодня no toxic productivity twitter. Rest.',
  'Learned new cooking trick. Domestic alpha.',
  'Сегодня smiled mirror practice cringe ok.',
  'Heard «love you» family. Rich.',
  'Сегодня no midnight snack guilt. Ate mindful.',
  'Planned morning walk. Future fit.',
  'Сегодня no argue thermostat. Compromise home.',
  'Enjoyed starry sky few stars enough.',
  'Сегодня thanked body sleep. Recovery.',
  'Read comic strip laughed. Light content.',
  'Сегодня no flex relationship online. Private happy.',
  'Fixed squeaky door hinge oil. Silence golden.',
  'Сегодня heard wind chime neighbor. Aesthetic.',
  'Made playlist calm. Mood tool.',
  'Сегодня no compare childhood friend success. Own path.',
  'Shared ride cost fair. Fairness.',
  'Сегодня enjoyed tea sunset window.',
  'Said no extra commitment. Bandwidth saved.',
  'Сегодня no gossip family chat. Peace.',
  'Walked dog new route adventure small.',
  'Сегодня heard live jazz bar passby. Culture walk.',
  'Fixed phone cracked screen plan finally. Adulting delayed.',
  'Сегодня no impulse reaction email. Draft slept.',
  'Enjoyed homemade soup winter recipe summer craving.',
  'Сегодня thanked past self exercise habit.',
  'Read quote wall cafe. Inspiration free.',
  'Сегодня no toxic self comparison instagram story.',
  'Heard friend promotion celebrated message. Good friend xp.',
  'Сегодня planned screen break every 45m work.',
  'Ate colorful salad. Health aesthetic.',
  'Сегодня no late night gaming regret. Sleep priority.',
  'Organized bag tomorrow. Morning smooth.',
  'Сегодня smiled barista remembered order. Community small.',
  'Enjoyed rain smell pavement. Petrichor fan.',
  'Сегодня no argue meme politics. Scroll past.',
  'Fixed loose tile foot safe. Home maintenance.',
  'Сегодня called friend «thinking of you». Nice.',
  'Walked barefoot grass park. Grounding.',
  'Сегодня no brag steps. Just walked.',
  'Heard kid say something wise accidentally. Learn.',
  'Сегодня enjoyed silence car park before enter home transition.',
  'Made bed morning. Habit chain.',
  'Сегодня no caffeine after 2pm challenge.',
  'Thanked delivery no tip shame fair wage support words.',
  'Сегодня read fiction not whitepaper refresh.',
  'Enjoyed friend hug meet. Human API.',
  'Сегодня no impulse buy gadget ad. Saved.',
  'Planned healthy dinner ingredients bought.',
  'Сегодня heard thunder far safe cozy.',
  'Fixed lamp flicker. No horror movie home.',
  'Сегодня no negative self label. Neutral describe.',
  'Shared funny story dinner table. Family lol.',
  'Сегодня walked phone silent. Brave modern human.',
  'Enjoyed moonrise photo friend sent. Connection.',
  'Сегодня no toxic hustle mindset guilt rest.',
  'Learned neighbor dog name. Community micro.',
  'Сегодня thanked rain for garden not trading mood.',
  'Read kids book niece. Wholesome reset.',
  'Сегодня no compare vacation photos. Joy own plan.',
  'Heard «you matter» friend drunk sincere still nice.',
  'Сегодня fixed posture reminder hourly. Neck thanks.',
  'Enjoyed ice cream small portion no guilt.',
  'Сегодня no midnight chart unless alert justified none.',
  'Made gratitude voice note self. Cringe therapeutic.',
  'Сегодня life good port meh ok post.',
];

function communityLinkAttachment(c, title) {
  return {
    title: (title || c.name).slice(0, 120),
    url: `/community/${c.handle}`,
  };
}

const ADVICE = [
  'Совет дня: риск на сделку 1–2% — так ты доживёшь до следующего цикла.',
  'Не усредняйся без плана. План = где добавляешь и где стоп.',
  'Funding экстремальный? Уменьши плечо, не увеличивай уверенность.',
  'Веди журнал сделок хотя бы неделю — увидишь паттерны ошибок.',
  'Перед входом спроси: «что invalidates идею?» Если не знаешь — не входи.',
  'Стейблы — не «навсегда 1$». Смотри depeg историю и ликвидность.',
  'Altcoin сезон обычно после ETH/BTC strength. Не торопи нарратив.',
  'Ликвидность тонкая — slippage съест edge. Проверяй depth.',
  'Новости = волатильность. Размер позиции режь, не стоп расширяй.',
  'Take-profit частями лучше, чем один идеальный выход.',
  'Спи нормально. Уставший трейдер — charity для рынка.',
  'Не торгуй revenge после минуса. Перерыв 30 мин минимум.',
  'Correlation растёт в панике — «диверсификация» может не спасти.',
  'On-chain: смотри exchange inflow перед дампом нарративом.',
  'Perp: funding + OI вместе, не по отдельности.',
  'Мемкоин: размер маленький, тезис короткий, выход заранее.',
  'BTC доминация растёт — альты часто кровоточат. Учитывай beta.',
  'Макро неделя: уменьши плечо до события, не после.',
  'Не верь скринам PnL без контекста size и времени.',
  'Community > lone wolf: обсуждай идеи, не только копируй.',
  'Tip: risk 1–2% per trade so you survive the cycle.',
  'Average down only with written rules.',
  'Extreme funding? Shrink size, not increase ego.',
  'Journal trades one week — patterns appear.',
  'Ask what invalidates the thesis before entry.',
  'Stables can depeg — check liquidity and history.',
  'Alt season often follows ETH/BTC — patience.',
  'Thin book eats edge — check depth.',
  'News week: cut size before event.',
  'Scale out beats one perfect exit.',
  'Sleep > extra candle tonight.',
  'No revenge trades. Walk 30 min.',
  'In panic, correlations spike — hedges matter.',
  'Exchange inflows can precede sells — watch flows.',
  'Funding + OI together for perps.',
  'Memecoin: small size, short thesis, planned exit.',
  'Rising BTC dominance often hurts alts.',
  'Macro week: de-lever before, not after headline.',
  'Screenshots aren\'t strategy — context matters.',
  'Discuss ideas in community, don\'t only copy.',
  'Стоп не «в голове» — в ордере. Иначе это пожелание.',
  'Не гонись за каждым тикером. Watchlist 10–15 max.',
  'Profit take на радости тоже profit take.',
  'Leverage умножает ошибки быстрее, чем правоту.',
  'Читай token unlock calendar — supply shock real.',
  'Bridge risk — не только APY.',
  'L2 fees падают — активность может вернуться. Следи нарратив.',
  'Airdrop farm: security > points.',
  'Restaking — понимай slashing risk, не только yield.',
  'NFT: liquidity exit plan before entry.',
  'Taxes/учёт сделок — boring until needed.',
  'Не все «alpha leaks» альфа. Filter.',
  'Spot first, perps when calm — progression.',
  'Correlation BTC: alts — check before size.',
  'Stop in order not in mind.',
  'Watchlist 10–15 tickers max.',
  'Taking profit on joy still counts.',
  'Leverage multiplies mistakes faster than wins.',
  'Unlock calendar matters — supply shocks.',
  'Bridge risk beyond APY.',
  'L2 fee drops can revive narratives.',
  'Airdrop: security > points.',
  'Restaking: know slashing.',
  'NFT: exit liquidity plan first.',
  'Track trades for taxes before chaos.',
  'Not every leak is alpha.',
  'Spot before perps when learning.',
  'Check BTC correlation before alt size.',
];

const PROMO = [
  { content: 'Сегодня в {name} разбор недели по {topic}. Вход бесплатный.', linkTitle: '{name}' },
  { content: 'Кто в теме {topic} — заходи в {name}. Живые треды, без спама.', linkTitle: '{name}' },
  { content: 'Запустили ветку «вопрос-ответ» в {name}. Новичкам welcome.', linkTitle: '{name}' },
  { content: 'В {name} выложили чеклист риск-менеджмента.', linkTitle: 'Чеклист в {name}' },
  { content: 'Обсуждаем мемы и риск в {name} — баланс редкий.', linkTitle: '{name}' },
  { content: 'Weekly recap в {name} уже в ленте сообщества.', linkTitle: '{name}' },
  { content: 'Ищешь людей по {topic}? Заходи в {name}.', linkTitle: '{name}' },
  { content: 'AMA в {name} сегодня вечером (community chat).', linkTitle: '{name}' },
  { content: 'Новый гайд по стейблам в {name}. Коротко и по делу.', linkTitle: '{name}' },
  { content: 'Degen но с правилами — {name}.', linkTitle: '{name}' },
  { content: 'Live thread on perps in {name}.', linkTitle: '{name}' },
  { content: 'Memecoin scans posted in {name}.', linkTitle: '{name}' },
  { content: 'Macro brief RU/EN in {name}.', linkTitle: '{name}' },
  { content: 'Risk checklist drop in {name}.', linkTitle: '{name}' },
  { content: 'SOL rotations chat in {name}.', linkTitle: '{name}' },
  { content: 'DeFi yields with risk notes — {name}.', linkTitle: '{name}' },
  { content: 'Funding arb ideas (educational) in {name}.', linkTitle: '{name}' },
  { content: 'On-chain flows daily pin in {name}.', linkTitle: '{name}' },
  { content: 'Trading journal prompts in {name}.', linkTitle: '{name}' },
  { content: 'New members intro thread — {name}.', linkTitle: '{name}' },
];

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randomTime() {
  const h = 6 + Math.floor(Math.random() * 18);
  const m = Math.floor(Math.random() * 60);
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;
}

function fillPromoFields(text, community) {
  return text
    .replace(/\{name\}/g, community.name)
    .replace(/\{handle\}/g, community.handle)
    .replace(/\{topic\}/g, community.topic);
}

/**
 * @returns {import('./seedFeed').PostSpec[]}
 */
function generateMay21Posts(count = 200) {
  const posts = [];
  const usedContent = new Set();

  const quotas = {
    humor: Math.round(count * 0.45),
    life: Math.round(count * 0.22),
    advice: Math.round(count * 0.18),
    promo: count - Math.round(count * 0.45) - Math.round(count * 0.22) - Math.round(count * 0.18),
  };

  const queues = [
    ...Array.from({ length: quotas.humor }, () => 'humor'),
    ...Array.from({ length: quotas.life }, () => 'life'),
    ...Array.from({ length: quotas.advice }, () => 'advice'),
    ...Array.from({ length: quotas.promo }, () => 'promo'),
  ];

  // shuffle queues
  for (let i = queues.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [queues[i], queues[j]] = [queues[j], queues[i]];
  }

  let humorIdx = 0;
  let lifeIdx = 0;
  let adviceIdx = 0;
  let promoIdx = 0;

  for (let i = 0; i < count; i++) {
    const kind = queues[i] || pick(['humor', 'humor', 'life', 'advice', 'promo']);
    const community = COMMUNITIES[i % COMMUNITIES.length];
    const username = USERNAME_POOL[i % USERNAME_POOL.length];
    let content = '';
    let linkAttachment = null;

    if (kind === 'humor') {
      content = HUMOR[humorIdx % HUMOR.length];
      humorIdx++;
      if (Math.random() > 0.65) {
        linkAttachment = communityLinkAttachment(community, `Зайти в ${community.name}`);
      }
    } else if (kind === 'life') {
      content = LIFE[lifeIdx % LIFE.length];
      lifeIdx++;
      if (Math.random() > 0.75) {
        content += ` P.S. Вечером загляну в ${community.name}.`;
        linkAttachment = communityLinkAttachment(community);
      }
    } else if (kind === 'advice') {
      const tpl = ADVICE[adviceIdx % ADVICE.length];
      adviceIdx++;
      content = tpl;
      if (Math.random() > 0.4) {
        linkAttachment = communityLinkAttachment(
          community,
          Math.random() > 0.5 ? community.name : `Совет в ${community.name}`
        );
      }
    } else {
      const tpl = PROMO[promoIdx % PROMO.length];
      promoIdx++;
      content = fillPromoFields(tpl.content, community);
      linkAttachment = communityLinkAttachment(
        community,
        fillPromoFields(tpl.linkTitle, community)
      );
    }

    const dedupeKey = `${content}||${linkAttachment?.url || ''}`;
    if (usedContent.has(dedupeKey)) {
      content = `${content} · #${i + 1}`;
    }
    usedContent.add(dedupeKey);

    const likes = Math.floor(Math.random() * 18);
    const reposts = Math.random() > 0.82 ? Math.floor(Math.random() * 5) + 1 : 0;

    const spec = {
      username,
      publishedAt: `21.05.2026 ${randomTime()}`,
      content,
      likes,
      reposts,
    };
    if (linkAttachment) spec.linkAttachment = linkAttachment;
    posts.push(spec);
  }

  return posts;
}

module.exports = { generateMay21Posts, COMMUNITIES };
